services:
  pgadmin:
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: "gol@p.lodz.pl"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "80:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: GoLdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
  pgadmin: